In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/air-quality-and-health-impact-dataset/air_quality_health_impact_data.csv


In [2]:
# Veri setini dataFrame'e dönüştürelim

df = pd.read_csv('/kaggle/input/air-quality-and-health-impact-dataset/air_quality_health_impact_data.csv')
pd.set_option('max_colwidth', 100)
df.head(5)

RecordID         AQI        PM10       PM2_5         NO2        SO2  \
0         1  187.270059  295.853039   13.038560    6.639263  66.161150   
1         2  475.357153  246.254703    9.984497   16.318326  90.499523   
2         3  365.996971   84.443191   23.111340   96.317811  17.875850   
3         4  299.329242   21.020609   14.273403   81.234403  48.323616   
4         5   78.009320   16.987667  152.111623  121.235461  90.866167   

           O3  Temperature   Humidity  WindSpeed  RespiratoryCases  \
0   54.624280     5.150335  84.424344   6.137755                 7   
1  169.621728     1.543378  46.851415   4.521422                10   
2    9.006794     1.169483  17.806977  11.157384                13   
3   93.161033    21.925276  99.473373  15.302500                 8   
4  241.795138     9.217517  24.906837  14.534733                 9   

   CardiovascularCases  HospitalAdmissions  HealthImpactScore  \
0                    5                   1          97.244041   
1                    2                   0         100.000000   
2                    3                   0         100.000000   
3                    8                   1         100.000000   
4                    0                   1          95.182643   

   HealthImpactClass  
0                0.0  
1                0.0  
2                0.0  
3                0.0  
4                0.0

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier

import warnings
warnings.filterwarnings('ignore')

In [4]:
# Özellikler (X) ve hedef değişken (y)
X = df.drop('HealthImpactClass', axis=1)
y = df['HealthImpactClass']

In [5]:
# Veriyi %80 eğitim ve %20 test setlerine ayırılır

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=58)

Logistic Regression genellikle özellik ölçeklendirmesine duyarlı bir algoritma olduğundan, önce özellikleri ölçeklendireceğiz ve ardından Logistic Regression modelini eğiteceğiz.

In [6]:
# Özellikleri ölçeklendirmesi

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
# Logistic Regression modelini oluşturulması ve eğitim

classifier = OneVsRestClassifier(LogisticRegression())
classifier.fit(X_train, y_train)

OneVsRestClassifier(estimator=LogisticRegression())

In [8]:
# Tahminleri ve olasılık tahminlerini alınır

y_pred = classifier.predict(X_test)

In [9]:
# Classification Report
print('Classification Report:')
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

         0.0       0.95      0.99      0.97       966
         1.0       0.68      0.77      0.72       111
         2.0       0.72      0.32      0.44        56
         3.0       0.00      0.00      0.00        14
         4.0       0.00      0.00      0.00        16

    accuracy                           0.91      1163
   macro avg       0.47      0.42      0.43      1163
weighted avg       0.89      0.91      0.90      1163



In [10]:
# Confusion Matrix
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[960   5   1   0   0]
 [ 24  85   2   0   0]
 [  8  29  18   0   1]
 [  6   4   4   0   0]
 [ 14   2   0   0   0]]
