In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/air-quality-and-health-impact-dataset/air_quality_health_impact_data.csv


In [2]:
df = pd.read_csv('/kaggle/input/air-quality-and-health-impact-dataset/air_quality_health_impact_data.csv')
pd.set_option('max_colwidth', 100)
df.head(5)

RecordID         AQI        PM10       PM2_5         NO2        SO2  \
0         1  187.270059  295.853039   13.038560    6.639263  66.161150   
1         2  475.357153  246.254703    9.984497   16.318326  90.499523   
2         3  365.996971   84.443191   23.111340   96.317811  17.875850   
3         4  299.329242   21.020609   14.273403   81.234403  48.323616   
4         5   78.009320   16.987667  152.111623  121.235461  90.866167   

           O3  Temperature   Humidity  WindSpeed  RespiratoryCases  \
0   54.624280     5.150335  84.424344   6.137755                 7   
1  169.621728     1.543378  46.851415   4.521422                10   
2    9.006794     1.169483  17.806977  11.157384                13   
3   93.161033    21.925276  99.473373  15.302500                 8   
4  241.795138     9.217517  24.906837  14.534733                 9   

   CardiovascularCases  HospitalAdmissions  HealthImpactScore  \
0                    5                   1          97.244041   
1                    2                   0         100.000000   
2                    3                   0         100.000000   
3                    8                   1         100.000000   
4                    0                   1          95.182643   

   HealthImpactClass  
0                0.0  
1                0.0  
2                0.0  
3                0.0  
4                0.0

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

In [4]:
# Özellikler (X) ve hedef değişken (y)

X = df.drop('HealthImpactClass', axis=1)
y = df['HealthImpactClass']

In [5]:
# Train-test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=58)

In [6]:
# Random Forest modeli oluşturma ve eğitme

rf_model = RandomForestClassifier(n_estimators=100, random_state=58)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=58)

In [7]:
# Test seti üzerinde tahmin yapma
y_pred = rf_model.predict(X_test)

In [8]:
# Model başarısını değerlendirme

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.96


In [9]:
# Confusion matrix

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[961   1   2   2   0]
 [  3 104   2   2   0]
 [  6   8  41   1   0]
 [  1   1   3   8   1]
 [  6   4   2   2   2]]


In [10]:
# Classification report

class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

         0.0       0.98      0.99      0.99       966
         1.0       0.88      0.94      0.91       111
         2.0       0.82      0.73      0.77        56
         3.0       0.53      0.57      0.55        14
         4.0       0.67      0.12      0.21        16

    accuracy                           0.96      1163
   macro avg       0.78      0.67      0.69      1163
weighted avg       0.96      0.96      0.96      1163

